docker pull mysql:5.7.33
docker pull holisun/bieco-orchestrator:0.2.0
docker pull holisun/bieco-ui:0.2.0
docker pull holisun/mock-tool:0.2.0
docker pull emiliacioroaica/ps_prototype:latest
docker pull rmohr/activemq:latest
docker pull rpiliszek7b/bieco_security_scorer_api:latest
docker pull rpiliszek7b/bieco_security_scorer_integrator:latest
docker pull harbor.gradiant.org/syp-bieco-pr-01333/fuzzing-tool:latest
docker pull harbor.gradiant.org/syp-bieco-pr-01333/forecasting-tool
docker pull harbor.gradiant.org/syp-bieco-pr-01333/detection-tool
docker pull harbor.gradiant.org/syp-bieco-pr-01333/propagation-tool
docker pull dridix/umu-bieco:umu-image
docker pull acalabro/concern:bieco
docker pull saiddao/ontologymanager:latest
docker pull ovidiucosmabm/fpt:version4